title: Your Blog Name
description: A brief description of your blog
author: Your Name
email: your.email@example.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# URL settings (replace with your username)
url: "https://yourusername.github.io"
baseurl: ""

# Social links (optional)
github_username: yourusername
twitter_username: yourtwitter

# Pagination
paginate: 5
paginate_path: "/page:num/"
